### PR TITLE
Fix to work with latest electron

### PR DESCRIPTION
**Pull request by YurySolovyov**
Hey, thanks for creating this, I updated some calls to work with latest electron.
Not sure if I can destructure electron thing, but I can make the changes if you tell me how.

### CODE REVIEW

**Comment by martinklepsch** [comment]
Hey @YurySolovyov thanks for working on this! 👍 

> Not sure if I can destructure electron thing, but I can make the changes if you tell me how.

Not sure what you mean here, are you referring to `app` & `BrowserWindow`? If so these can't be destructured and have to be retrieved via interop forms (like you did).

How have you tested this? I don't have the capacity right now to test myself but if you say it's working I'll trust you and merge it :) Thanks again!

**Comment by YurySolovyov** [comment]
@martinklepsch I did

```
boot watch dev-build
```

and then

```
electron target
```

works for me :)

**Comment by martinklepsch** [comment]
@YurySolovyov thank you very much! 👍

**Comment by YurySolovyov** [comment]
@martinklepsch I can also try to update main deps to latest stables and submit PR if it works

**Comment by martinklepsch** [comment]
@YurySolovyov you are more than welcome to :)

**Pull request merged**
